# Generated by Django 3.2.7 on 2021-09-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sale',
        ),
    ]
