# Generated by Django 3.2.7 on 2021-10-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_good_orderitem_product'),
        ('mainapp', '0004_auto_20211006_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='Product',
        ),
    ]
