# Generated by Django 3.2.7 on 2021-10-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211011_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='products',
            new_name='product',
        ),
    ]
