# Generated by Django 3.2.7 on 2021-10-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_product_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
