# Generated by Django 3.2.7 on 2021-10-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='good',
            new_name='product',
        ),
    ]
