# Generated by Django 3.2.7 on 2021-10-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_good_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveries',
            field=models.CharField(choices=[('Доставка', 'Доставка'), ('Самовывоз', 'Самовывоз')], default=1, max_length=10, verbose_name='Опция доставки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Фамилия'),
        ),
    ]
