# Generated by Django 3.2.7 on 2021-10-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211011_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(default=1, max_length=200, verbose_name='Комментарии к заказу'),
            preserve_default=False,
        ),
    ]
