# Generated by Django 3.2.7 on 2021-10-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
